blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/asq-sheriff/MultiDB-Chatbot/discussions
    about: Please ask questions in GitHub Discussions instead of Issues.

