name: Feature request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
assignees: ["asq-sheriff"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: What would you like to see added?
      placeholder: "Support for another vector database..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important? What problem does it solve?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other approaches have you thought about?

